server:
  port: 8080
  servlet:
    context-path: /livraria

spring:
  # DATASOURCE
  datasource:
    url: jdbc:h2:mem:teste
    driverClassName: org.h2.Driver
    username: sa
    password: password
# H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
#JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: update
